### ISSUE TITLE
Error: AttributeError: 'NoneType' object has no attribute 'location'

### ISSUE THREAD

**Issue by SahandMoslemi** [Ringbo/Cache#5]
Hi. When I'm trying to run ```main.py```, the following error occurs:
```
Traceback (most recent call last):
  File "/home/Cache/source/main.py", line 286, in <module>
    main(args)
  File "/home/Cache/source/main.py", line 282, in main
    train()
  File "/home/Cache/source/main.py", line 98, in train
    reader = DatasetReader(args.dataset_path + "path_contexts.csv", args.dataset_path + "paths.csv",
  File "/home/Cache/source/model/dataset_reader_binary.py", line 76, in __init__
    self.load(corpus_path, testFlag)
  File "/home/Cache/source/model/dataset_reader_binary.py", line 104, in load
    if self.last_item.location == "/".join(fileInfo[:-1]):
AttributeError: 'NoneType' object has no attribute 'location'
```
I would appreciate your help.

**Comment by Ringbo** [comment]
Hi. It appears that `self.last_item` is None. Could you check the construction of `CodeData` in [here](https://github.com/Ringbo/Cache/blob/2569b2fc4bea0a6bc0aab05997e2e7f1f21ae98b/source/model/dataset_reader_binary.py#L83)? If the CodeData list is initialized successfully, self.last_item should not be None.
